language: node_js
sudo: false
node_js:
- stable
addons:
  firefox: '42.0'
cache:
  directories:
  - node_modules
before_script:
- npm install web-component-tester bower polylint
- bower install
- bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct
after_success: '[ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && bower_components/collaborne-build-tools/gpages_build.sh Collaborne info@collaborne.com'
env:
  secure: qDP9fpYHpe3YArUYRzedsiXpNQM7Kc6wyl0hhJaFPl7zjeKmbOBpFYhxMkA354/cKlMchU4zUFb9loByVYAEhSN8mYW6o2UUA7yrnUJ/lIiOI4XdR0SlJE8WnNO/Cfbvkho5Liw4+kZXNQLhlfE7GdstgPP/kmVynqA/K8WfpVdfbZKQ3IWbKzm0AeL8FWdlg/IjWAb4LYxttuWSMZUiEDlM/GXdsB2Pt5a9hKV+TR+tK5JtvXA9LtvTs6blDAnGXaWdKn6YpF+57g7MLIGIF+e0fGHek+F/8Z6/ptJc3gY14Vtmyy+FsrUtF4wQk3OGRGrQJK1PjLL16Ykdrq7R/YQ1DEIwFRYgw6zg4DX4aPJXscKsatPBYy24SdfudHfwzitMuaLaEl6CVun1qbODKYyQELxP/xzIYrg6TF/jOd/7N0TEH+yTVT6sXZv7y6MaS28CY/90dWW3/Zth9q0ikSb6e775vrwnnwTZaKXvmNEHsMky4zw1ydYm3PpIWOO54xnPxC4Xn5+wE5MZ8rdgVfivMtQ1qlzDU09Z6ese2GlXQMaE3UtcqE+F8hmnC0m/t0gyD/u7nxYzvwI+MiDZEmNu47EAc7sOe6oS7tpxtVIvA5eHfHcSkwPXyZQIUNpPR78inCW2fp8Ox1W/YxWXiY0nX/icTFWf70fHR/tFD8g=
